# Generated by Django 4.2.7 on 2024-02-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_options_and_more'),
        ('recepies', '0002_alter_recepie_recepie_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'вес продукта', 'verbose_name_plural': 'вес продуктов'},
        ),
        migrations.AlterModelOptions(
            name='recepie',
            options={'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recepie',
            name='product',
            field=models.ManyToManyField(through='recepies.Quantity', to='products.product'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='recepie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.recepie', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='weight',
            field=models.IntegerField(verbose_name='Вес продукта'),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='recepie_image',
            field=models.ImageField(upload_to='recepie_images', verbose_name='Изображение рецепта'),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='recepie_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='username_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
